### ISSUE TITLE
Merge with samsung_print

### ISSUE THREAD

**Issue by fabaff** [nielstron/pysyncthru#2]
A couple of weeks ago I published something similar: https://pypi.python.org/pypi/samsung_print

I guess that it would be best if we merge pysyncthru and [samsung-print](https://github.com/fabaff/samsung-print) and work on this as a joined effort to save resources.

**Comment by nielstron** [comment]
Didn't get your example.py working on python3.6
```
Traceback (most recent call last):
  File "C:\Users\user\git\samsung-print\example.py", line 21, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python36\lib\asyncio\base_events.py", line 438, in run_until_complete
    return future.result()
  File "C:\Program Files\Python36\lib\asyncio\futures.py", line 292, in result
    raise self._exception
  File "C:\Program Files\Python36\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\user\git\samsung-print\example.py", line 13, in main
    with aiohttp.ClientSession() as session:
  File "C:\Program Files\Python36\lib\site-packages\aiohttp\client.py", line 742, in __enter__
    raise TypeError("Use async with instead")
TypeError: Use async with instead
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020AA5C41400>
```
Also `async with...` won't compile...
